# Generated by Django 6.0.5 on 2026-06-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('certificate', models.CharField(blank=True, max_length=20)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('meta_score', models.IntegerField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('gross', models.BigIntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
                ('actors', models.ManyToManyField(blank=True, related_name='acted_movies', to='movies.person')),
                ('directors', models.ManyToManyField(blank=True, related_name='directed_movies', to='movies.person')),
            ],
            options={
                'ordering': ['-imdb_rating'],
                'constraints': [models.UniqueConstraint(fields=('title', 'year'), name='unique_movie_title_year')],
            },
        ),
    ]
